### ISSUE TITLE
Implement hello world app + travis config

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/app-electron#1]
For the first PR let's aim for the following:
- a hello world electron app, whatever that looks like
- Travis CI config file, electron has a [doc page](http://electron.atom.io/docs/tutorial/testing-on-headless-ci/) for this
  - at first, just have it run eslint (use the same config file as the [main repo](https://github.com/zen-audio-player/zen-audio-player.github.io/blob/master/.eslintrc.json))
- update `README.md` with development notes

**Comment by shakeelmohamed** [comment]
@artforlife update the readme to mention `npm start` and we can close this

**Comment by artforlife** [comment]
I created a PR. By the way, am I supposed to be able to make changes to this repo after joining the organization?

**Comment by shakeelmohamed** [comment]
@artforlife No, I thought about allowing it on all repos after GitHub added finer grain branch permissions. The main reason is so I have to manually merge every PR after reviewing it. The fork model works well enough with GitHub and nobody has complained so far

**Comment by shakeelmohamed** [comment]
All done!
